# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Rishav Kumar
title: Design Verification Engineer
email: kumarrishav14@outlook.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: kumarrishav14
github_username: kumarrishav14
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: kumarrishav14
linkedin_username: kumarrishav14
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "UA-185652507-1"
# google_analytics: "UA-185652507-1"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, I'm an Electronics Engineer, having a background as a Quality Engineer in Midea India Pvt. Ltd. Currently, I am developing my VLSI skills, especially in the Design Verification field. I keep an interest in electronics, digital systems, and coding. I also develop apps - 555 timer is one of the apps that I recently created.

  My Skills: <mark>Design Verification</mark>, <mark>SV</mark> and <mark>UVM</mark> as well.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: AMBA AXI
        link: https://kumarrishav14.github.io/AXI/
        link_text: Link to Project Website
        additional_links:
          - title: kumarrishav14/amba-axi
            icon: fab fa-github
            url: github.com/kumarrishav14/AXI
        quote: >
          VIP for AXI Protocol
        description: | # this will include new lines to allow paragraphs
          Developed a VIP for AXI 3 protocol from scratch, i.e, starting from Testbench arctitecture, Test plan, Feature Extraction. Highly Configurable VIP with support of variable address and data width. Presently, the test suite includes basic burst transactions.

          Key Concepts learned: <mark>AXI Protocol</mark> <mark>Burst transfers</mark> <mark>Complex testbench design</mark> <mark>VIP Concept</mark>

      - layout: top-middle
        title: APB
        link: https://kumarrishav14.github.io/AMBA_APB/
        link_text: Link to Project Website
        additional_links:
          - title: kumarrishav14/AMBA_APB
            icon: fab fa-github
            url: github.com/kumarrishav14/AMBA_APB
        quote: >
          This was the most challenging project which I had done during this training.
        description: | # this will include new lines to allow paragraphs
          APB, also is the part of my training in <b>Design Verification</b>. This is a complete testbench with and without UVM for a single APB slave cofiguration, where DUT is a single port RAM. Through this project, I learnt a lot about the AMBA specifications, especially <b>APB</b> protocols. Apart from protocol, it gave me a hands-on experience to design the complete testbench architecture from scratch along with the test plan. Also, I got to know the advantage of using UVM to design Test bench over raw SV test bench.

          Key concepts learned: <mark>APB protocol</mark> <mark>Debugging</mark> <mark>TB Architecutre Design</mark>

      - layout: top-middle
        title: ALU UVM
        link: https://kumarrishav14.github.io/ALU_UVM/
        link_text: Link to Project Website
        additional_links:
          - title: kumarrishav14/alu-uvm
            icon: fab fa-github
            url: github.com/kumarrishav14/ALU_UVM
        quote: >
          This was one of my first UVM Project.
        description: | # this will include new lines to allow paragraphs
          ALU UVM is a part of my training in <b>Design Verification</b>. I developed the testbench for 8-bit ALU, which is easily configurable. I explored different UVM components while doing this project specially about <b>TLM Ports</b> and <b>UVM Reporting</b>

      - layout: top-middle
        quote: >
          Please visit my <a href="https://github.com/kumarrishav14">GitHub</a> for more projects.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sion Semiconductors Pvt Ltd
        link:
        sub_title: SOC Verification Intern
        caption: Mar 2021 - Jun 2021
        quote: >
          Sion Semiconductor has extended its services to complete Product engineering space from concept to product realisation and is the OEM for many Tier-1 companies.
        description: | # this will include new lines to allow paragraphs
          As an intern in Sion Semiconductor, I was involved in a project to make VIP for ARM Watchdog timer. This project gave me a good experience of implementing a test bench with RAL integration.

          Skills gained: <mark>UVM RAL</mark> <mark>Coverage</mark>

      - layout: left
        title: Midea India Pvt. Ltd
        link: https://www.midea-group.com/
        # link_text: boringcompany.com
        sub_title: Quality Engineer
        caption: Jun 2019 - Jul 2020
        quote: >
          Midea Group is a leading technology company specializing in Robotics, Industrial Automation, HVAC Systems, Consumer Appliances and Smart Logistics and Midea India is a new venture of the group in India.
        description: | # this will include new lines to allow paragraphs
          As a fresh graduate, I got six months of training in the Quality Department of Midea China factory. This training gave me exposure to vast technical experience. Apart from the technical environment, I learned to work in a multi-cultured social environment too. After completing my training, I worked in BIS, and ISO certification of India plant, during which I made/translated 50-60 ISO documents and shop floor documents.

          Skills gained: <mark>Quality Principles</mark> <mark>Six Sigma</mark> <mark>Presentation</mark> <mark>Documentation</mark>

      - layout: left
        title: Integrated Test Range, DRDO
        link: https://www.drdo.gov.in/labs-and-establishments/integrated-test-range-itr
        link_text: drdo.gov.in
        sub_title: Summer Trainee
        caption: Mar 2018 - Jun 2018
        quote: >
          ITR is a facility operated and maintained by DRDO, GoI. ITR provides launch and test facilties for rockets, missiles, and air-borne weapon system.
        description: | # this will include new lines to allow paragraphs
          I worked in the telecommand division of ITR, which focuses on sending commands to the test device. Our assigned project aimed to develop an indigenous AGC (Automatic Gain Controller) for a 10W transmitter. This project gave us many insights about the transmitter's working and the need for AGCs in the transmitter. Also, I got hands-on experience with high-end oscilloscopes, function generators, and spectrometers.

          Skills gained: <mark>Telecommand Principles</mark> <mark>AGCs</mark> <mark>Testing of Ciruits</mark>

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Kalinga Institute of Industrial Technology
        caption: 2015 - 2019
        sub_title: B. Tech Electronics and Telecommunications
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my college, I was deeply involved in various projects, mainly of research background. My academic project was a research-based project on MIMO Scheduling, titled "Scheduling of users in MIMO communication using PSO"

          <b>MIMO</b> (Multiple Input Multiple Output) is the key principle for 5G communication and scheduling of users in MIMO is the biggest challenge in base station due to the high computational power required. In this project, we used PSO technique to schedule the users with less computational power.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      To have a focused mind, we need a balance in all domains of our life. Besides my career in electronics and software fields, I also give priority to my hobbies and interests. I like to explore new places that are underestimated by tourists. In my free time, I try my hand at cooking and doodling.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
