# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Rishav Kumar
title: Engineer
email: kumarrishav14@outlook.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: kumarrishav14
github_username:  kumarrishav14
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: kumarrishav14
linkedin_username: kumarrishav14
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "UA-185652507-1"
# google_analytics: "UA-185652507-1"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Rishav and was working as a Quality Engineer. Currently i am devleoping my skills in VLSI specially in the Design Verification field. Apart from having keen interest in electronic and digital system, I have also interest in coding and making apps.

  I am most skilled in: <mark>Design Verification</mark>, <mark>SV</mark> and <mark>UVM</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: ALU UVM
        link: https://kumarrishav14.github.io/ALU_UVM/
        link_text: Project Website
        additional_links:
          - title:  kumarrishav14/alu-uvm
            icon: fab fa-github
            url: github.com/kumarrishav14/ALU_UVM
        quote: >
          This is one of my first UVM Projects
        description: | # this will include new lines to allow paragraphs
          I did this project as part of my training in <mark>Design Verification</mark>. The testbecnh developed is for 8-bit ALU which is easily configurable. I learned a lot about the different UVM components through this project specially about <b>TLM Ports</b> and <b>UVM Reporting</b><hr>

      - layout: top-middle
        title: APB SV
        link: https://kumarrishav14.github.io/ALU_UVM/
        link_text: Project Website
        additional_links:
          - title:  kumarrishav14/alu-uvm
            icon: fab fa-github
            url: github.com/kumarrishav14/ALU_UVM
        quote: >
          This is the most challenging project done by me.
        description: | # this will include new lines to allow paragraphs
          This project was also done by me as part of my training in <mark>Design Verification</mark>. This is a complete SV testbench (without using UVM) for a single APB slave cofiguration (slave is taken as memory). Through this project i learnt a lot about the AMBA specifications specially <b>APB</b> protocols. Apart from protocol, it gave me a hand on experience to design the complete test bench architecture from scratch along with the test plan. 

          Key concepts learned: <mark>APB protocol</mark> <mark>Debugging</mark> <mark>TB Architecutre Design</mark> 

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Midea India Pvt. Ltd
        link: https://www.midea-group.com/
        # link_text: boringcompany.com
        sub_title: Quality Engineer
        caption: Jun 2019 - Jul 2020
        quote: >
          Midea Group is a leading technology company specializing in Robotics, Industrial Automation, HVAC Systems, Consumer Appliances and Smart Logistics and Midea India is a new venture of the group in India.
        description: | # this will include new lines to allow paragraphs
          I got into this company as a fresh graduate and got 6 months training in Quality Department of Midea China factory. This training gave me lot of technical experience but at the same time it teached me to handle the cross culture difference. After successfull completion of my training I was involved in BIS and ISO certification of India plant, during which I made/translated 50-60 ISO documents and shop floor documents.

          Skills gained: <mark>Quality Principles</mark> <mark>Six Sigma</mark> <mark>Presentation</mark> <mark>Documentation</mark>

      - layout: left
        title: Integrated Test Range, DRDO
        link: https://www.drdo.gov.in/labs-and-establishments/integrated-test-range-itr
        link_text: drdo.gov.in
        sub_title: Summer Trainee
        caption: Mar 2018 - Jun 2018
        quote: >
          ITR is a facility operated and maintained by DRDO, GoI. ITR provides launch and test facilties for rockets, missiles and air-borne weapon system.
        description: | # this will include new lines to allow paragraphs
          I worked in the telecommand division of ITR, which is mainly focused on sending commands to the test device. My team was assigned the project to develope a indigeneous <b>AGC</b> (Automatic Gain controller) for 10W transmitter. This project gave me a lot of insights about the working of transmitter and the need for AGCs in transmitter. Also, I got hands on experience with high end oscilloscopes, function generator and spectrometers.

          Skills gained: <mark>Telecommand Principles</mark> <mark>AGCs</mark> <mark>Testing of ciruits</mark>
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Kalinga Institute of Industrial Technology
        caption: 2015 - 2019
        sub_title: B. Tech Electronic and Telecommunications
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my college, i was deeply involved in various projects, mainly of research back ground. My academic project was a research based project on MIMO Scheduling. 

          <b>MIMO</b> (Multiple Input Multiple Output) is the key principle for 5G communication and scheduling of users in MIMO is the biggest challenge in base station due to the high computational power required.  

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in electroics and software engineering some of my other interests and hobbies are:
      - Cooking
      - Learning new things

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
